### ISSUE TITLE
Speed limit while turning

### ISSUE THREAD

**Issue by alancnet** [ksqk34/Autodocking-2#5]
I would be interested in limiting the speed of rotation. I selected Cinematic speed because I'm parking a large ship in a tight spot, and when the gyros kicked in... well.... 

![image](https://user-images.githubusercontent.com/2042102/97797445-518dcc80-1bda-11eb-881a-e9a8bdbb179f.png)

:)

**Comment by Tom-A-Roberts** [comment]
I've added a rotation_speed variable. This should be set between 0 and 1, as a proportion of the normal rotation speed. The default being 1.
Hopefully it causes less carnage for you now ;)
